# Generated by Django 4.2.2 on 2023-07-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_address_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quarity',
            new_name='quantity',
        ),
    ]
